messages:
  - role: system
    content: You are a duplicate issue detector. You have access to GitHub MCP tools to read and search issues.
  - role: user
    content: |
      Find up to 3 likely duplicate issues for issue #{{issue_number}} in the acacode/swagger-typescript-api repository.

      To do this, follow these steps precisely:

      1. Read issue #{{issue_number}} including its comments. Check if the issue (a) is closed, (b) does not need to be deduped (e.g. because it is broad product feedback without a specific solution, or positive feedback), or (c) already has a duplicates comment containing `<!-- ai-duplicate-check -->`. If so, do not proceed — return an empty duplicates array.
      2. Summarize the issue: what is the core problem, symptoms, and affected features.
      3. Search for duplicates of this issue using diverse keywords and search approaches based on the summary. Try at least 5 different search queries to maximize coverage.
      4. Filter out false positives that are likely not actually duplicates of the original issue. If there are no duplicates remaining, return an empty duplicates array.
      5. Return the remaining duplicate issue numbers (up to 3), ranked by confidence (highest first).
model: openai/gpt-4o
responseFormat: json_schema
jsonSchema: |-
  {
    "name": "duplicate_detection_result",
    "strict": true,
    "schema": {
      "type": "object",
      "properties": {
        "duplicates": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Issue numbers of potential duplicates, ranked by confidence (highest first). Empty array if no duplicates found or issue should be skipped."
        }
      },
      "additionalProperties": false,
      "required": ["duplicates"]
    }
  }
