messages:
  - role: system
    content: You are a duplicate issue detector. Be extremely concise — never output lengthy analysis. Only output tool calls and the final JSON result.
  - role: user
    content: |
      Find up to 3 likely duplicate issues for issue #{{issue_number}} in the acacode/swagger-typescript-api repository.

      Steps:
      1. Read issue #{{issue_number}} and its comments. If the issue is closed, is broad feedback, or already has a comment containing `This issue will be automatically closed as a duplicate in 3 days.`, return an empty duplicates array immediately.
      2. Search for duplicates using 2 different search queries with perPage=3. Use diverse keywords based on the issue content.
      3. Filter out false positives and return up to 3 duplicate issue numbers, ranked by confidence.
model: openai/gpt-4o
responseFormat: json_schema
jsonSchema: |-
  {
    "name": "duplicate_detection_result",
    "strict": true,
    "schema": {
      "type": "object",
      "properties": {
        "duplicates": {
          "type": "array",
          "items": {
            "type": "integer"
          },
          "description": "Issue numbers of potential duplicates, ranked by confidence (highest first). Empty array if no duplicates found or issue should be skipped."
        }
      },
      "additionalProperties": false,
      "required": ["duplicates"]
    }
  }
