
language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

before_install:
  - export PACKAGE_VERSION=$(node -p "require('./package.json').version")
  - export PACKAGE_NAME=$(node -p "require('./package.json').name")
  - export NPM_REMOTE_VERSION=$(npm view swagger-typescript-api version)
  - export BRANCH_IS_TAG=$(node -p "/^([0-9].[0-9].[0-9]+((-(alpha|beta))|))$/.test('${TRAVIS_BRANCH}')")
  - export GIT_LOG="$(git log --pretty=format:"* %s (%h)")"
  - export PROJECT_NAME="acacode/swagger-typescript-api"

install:
  - npm ci

jobs:
  include:
    - stage: generate&validate
      script:
        - npm run test:all

notifications:
  slack:
    rooms:
      secure: vOYvagXgEbjgwSJaK70QU574OcUq1MyqJYJp08wqcLA2AUfxrN3HJj24s2qd3NAMIU2Zw6jfEwQBbH3vV10cwf2u5Yp9pAgbrLOJCV+1wixMJL6GxWLesbtUuizoOCEL+f5qogFPNpy4W2FDcG0DEYwuhLSdf5qToGXP5BSn3VPuvZYRhKRq9wJpeXNTLbu+XW8hEkuUpjbr2zzm+k8pCggONGVQ5SCSCI5DVHsCnsxzumwNcKbNitLiRMQKRJiFCOQ4YQwpZ7SCEu75YxMjb+UDIEYi5CtxgxCRaoBZfYj/uI4exxavmb0/vp5CJ1dTUNmI2R3pTQUIERoFXajl479FMnxhGsKycVG7O2hKqxNCDT8tPAzxdMaF31u7AtWajdZpmOLyAIc/RjUAJfuSlzT3hcSfZUQ23VOcf8Q/yJXVT6XqYPuEO8xhVXdCJN4PtDowjzeoMqZCTSmknrPcKGfvuY86rw5aIFngYy1TysR8fhDgpxqTmsrG2HOrVzmq4oLsEsm6jGqghvLM3x03HOxX6pdo/lDoaTl1lR0ZraC1tGvGQpb1M38GxNpWFmmqb0A7Q9aHK4OBddvEMEU1nivb2t41DQou3ga+czm8vo1o0cEXOczDQmCQhOrPn0/m5ud49rzMLfxhXQbT4fphuNAAbumn2dc2eKc3ZB3w4ng=