name: CI

on:
  pull_request:
    branches:
      - next

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: use node
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: install deps
        run: npm i

      - name: simple-tests
        run: npm run generate && npm run validate

      - name: specific-tests
        run: npm run test-specific
