name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [25, 24, 22, 20]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set-up Mise
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1.6.4.0.1
        with:
          cache: false
          mise_toml: |
            [tools]
            bun = "latest"
            node = "${{ matrix.node-version }}"
      - run: bun install --frozen-lockfile
      - run: bun run format:check
      - run: bun run build
      - run: bun run test
