name: Builds, tests & co

on:
  - push
  - pull_request

permissions: read-all

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        node-version: [25, 24, 22, 20]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Set-up Mise
        uses: jdx/mise-action@dba19683ed58901619b14f395a24841710cb4925 # v4.1.0.6.4.1.0
        with:
          cache: false
          mise_toml: |
            [tools]
            bun = "latest"
            node = "${{ matrix.node-version }}"
      - run: bun install --frozen-lockfile
      - run: bun run format:check
      - run: bun run build
      - run: bun run test
